force-app/main/default/objects/Case/fields/DataLimiteResolucao__c.field-meta.xml
<CustomField>
    <fullName>DataLimiteResolucao__c</fullName>
    <description>Fórmula baseada no Tempo de Resolução do SLA vinculado ao caso</description>
    <inlineHelpText>Data limite para resolução do caso conforme Tempo de Resolução padrão para criticidade selecionada</inlineHelpText>
    <label>Data Limite para Resolução</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Urgencia__c.field-meta.xml
<CustomField>
    <fullName>Urgencia__c</fullName>
    <description>Campo para registrar a criticidade (urgência) para a resolução do caso</description>
    <inlineHelpText>Selecione a criticidade para tratativa do caso</inlineHelpText>
    <label>Urgência</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baixa</fullName>
                <default>true</default>
                <label>Baixa</label>
            </value>
            <value>
                <fullName>Média</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchOverdueCasesTest.cls
@isTest
private class BatchOverdueCasesTest {
    @isTest
    static void testBatchProcessLateCases() {
        // Cria caso atrasado
        Case c = new Case(Urgencia__c = 'Baixa', DataLimiteResolucao__c = System.now().addMinutes(-5));
        insert c;
        Test.startTest();
        BatchOverdueCases batch = new BatchOverdueCases();
        Database.executeBatch(batch, 1);
        Test.stopTest();
        c = [SELECT Urgencia__c FROM Case WHERE Id = :c.Id];
        System.assertEquals('Alta', c.Urgencia__c, 'Urgência deve ser elevada para Alta');
    }
}